# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fdd07fdaa66e23c2fc708d8be8e5b4579c7f731599ae6449354f47c711cd0e3c9a75be01492d5f0ff03495939a61271ef85dfb8483ccb9663178ea3401487f4

test:
  secret_key_base: 10a3ad74c558fde14cf592dbbc284690c6ed7152df75cf61b89735d3e9d05f45e8560b7dbe6fdd6e62da6a8e335e3576e9b4fa93fdf27b1393e379d3a1c11d52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
