# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup, active: true).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }], active: true)
#   Mayor.create(name: 'Emanuel', city: cities.first, active: true)

Person.create(name: "Daniel Roseman", roles: ["primary_developer", "oncall_weekday_developer", "oncall_weekend_developer"], team: "Publishing Platform", active: true)
Person.create(name: "Andrew Garner", roles: ["primary_developer", "oncall_weekday_developer", "oncall_weekend_developer"], team: "Core Formats", active: true)
Person.create(name: "Jenny Duckett", roles: ["primary_developer", "oncall_weekday_developer", "oncall_weekend_developer"], team: "Custom", active: true)
Person.create(name: "Richard Boulton", roles: ["primary_developer", "oncall_weekday_developer", "oncall_weekend_developer"], team: "Finding Things", active: true)
Person.create(name: "Theo Vararu", roles: ["primary_developer", "oncall_weekday_developer", "oncall_weekend_developer"], team: "Other", active: true)
Person.create(name: "David Singleton", roles: ["primary_developer"], team: "Core Formats", active: true)
Person.create(name: "Nick Colley", roles: ["primary_developer"], team: "Publishing Platform", active: true)
Person.create(name: "Dai Vaughan", roles: ["primary_developer"], team: "Other", active: true)
Person.create(name: "Alex Muller", roles: ["infrastructure_developer", "oncall_weekday_developer", "oncall_weekend_developer"], team: "Infrastructure", active: true)
Person.create(name: "Christopher Baines", roles: ["infrastructure_developer", "oncall_weekday_developer", "oncall_weekend_developer"], team: "Infrastructure", active: true)
Person.create(name: "Laura Martin", roles: ["infrastructure_developer"], team: "Infrastructure", active: true)
Person.create(name: "Elliot Crosby-McCollough", roles: ["supplemental_developer"], team: "Publishing Platform", active: true)
Person.create(name: "Chris Patuzzo", roles: ["supplemental_developer"], team: "Publishing Platform", active: true)
Person.create(name: "Stephen Laing", roles: ["supplemental_developer"], team: "Publishing Platform", active: true)
Person.create(name: "David Basalla", roles: ["supplemental_developer"], team: "Custom", active: true)
Person.create(name: "Murray Steele", roles: ["supplemental_developer"], team: "Custom", active: true)
Person.create(name: "Rosa Fox", roles: ["supplemental_developer"], team: "Publishing Platform", active: true)
Person.create(name: "Issy Long", roles: ["supplemental_developer"], team: "Custom", active: true)
Person.create(name: "Brendan Butler", roles: ["supplemental_developer"], team: "Custom", active: true)
Person.create(name: "Simon Hughesdon", roles: ["supplemental_developer"], team: "Custom", active: true)
Person.create(name: "Jack Scotti", roles: ["supplemental_developer"], team: "Finding Things", active: true)
Person.create(name: "Paul Bowsher", roles: ["supplemental_developer"], team: "Core Formats", active: true)
Person.create(name: "David Silva", roles: ["supplemental_developer"], team: "Core Formats", active: true)
Person.create(name: "Paul Hayes", roles: ["supplemental_developer"], team: "Core Formats", active: true)
Person.create(name: "Rueben Arakelyan", roles: ["supplemental_developer"], team: "Finding Things", active: true)
Person.create(name: "Matt Moore", roles: ["supplemental_developer"], team: "Finding Things", active: true)
Person.create(name: "Leena Gupte", roles: ["supplemental_developer"], team: "Performance Platform", active: true)
Person.create(name: "Tatiana Stantonian", roles: ["supplemental_developer"], team: "Core Formats", active: true)
Person.create(name: "Tijmen Brommet", roles: ["supplemental_developer"], team: "Finding Things", active: true)
Person.create(name: "Mo Baig", roles: ["supplemental_developer"], team: "Finding Things", active: true)
Person.create(name: "Ben Hyland", roles: ["supplemental_developer"], team: "Finding Things", active: true)
Person.create(name: "Tim Blair", roles: ["oncall_weekday_developer", "oncall_weekend_developer"], team: "Other", active: true)
Person.create(name: "bob Walker", roles: ["oncall_weekday_developer", "oncall_weekend_developer"], team: "Infrastructure", active: true)
Person.create(name: "bob Walker2", roles: ["oncall_weekday_developer", "oncall_weekend_developer"], team: "Infrastructure", active: true)
Person.create(name: "bob Walker3", roles: ["oncall_weekday_developer", "oncall_weekend_developer"], team: "Infrastructure", active: true)
Person.create(name: "bob Walker4", roles: ["oncall_weekday_developer", "oncall_weekend_developer"], team: "Infrastructure", active: true)
Person.create(name: "bob Walker5", roles: ["oncall_weekday_developer", "oncall_weekend_developer"], team: "Infrastructure", active: true)
Person.create(name: "bob Walker6", roles: ["oncall_weekday_developer", "oncall_weekend_developer"], team: "Infrastructure", active: true)
Person.create(name: "bob Walker7", roles: ["oncall_weekday_developer", "oncall_weekend_developer"], team: "Infrastructure", active: true)
Person.create(name: "bob Walker8", roles: ["oncall_weekday_developer", "oncall_weekend_developer"], team: "Infrastructure", active: true)
Person.create(name: "bob Walker9", roles: ["oncall_weekday_developer", "oncall_weekend_developer"], team: "Infrastructure", active: true)
Person.create(name: "bob Walker10", roles: ["oncall_weekday_developer", "oncall_weekend_developer"], team: "Infrastructure", active: true)
Assignment.create(week: Week.create(start_date: Date.new(2016,05,18)), person: Person.create(name: "bob Walker10", roles: ["oncall_weekday_developer", "oncall_weekend_developer"], team: "Infrastructure", active: true))
Assignment.create(week: Week.create(start_date: Date.new(2016,05,25)), person: Person.create(name: "bob Walker11", roles: ["oncall_weekday_developer", "oncall_weekend_developer"], team: "Infrastructure", active: true))
